import {contracts as demoContracts} from '@/lib/demo-data';import {isDemoMode} from '@/lib/data-mode';import {prisma} from '@/lib/prisma';
export type ContractItem={id:string;number:string;property:string;party:string;type:string;amount:string;amountValue:number;commission:string;commissionValue:number;date:string;status:string};
type Input={number?:string;type:string;amount:number;commission:number;contractDate:string;status?:string;propertyId?:string;applicantId?:string;agentId?:string;notes?:string};
let store:ContractItem[]=demoContracts.map((c:any)=>({id:String(c.id),number:String(c.id),property:c.property,party:c.party,type:c.type,amount:c.amount,amountValue:0,commission:c.commission,commissionValue:0,date:c.date,status:c.status}));
const money=(v:number)=>`${new Intl.NumberFormat('fa-IR',{maximumFractionDigits:1}).format(v/1_000_000_000)} میلیارد`;
function mapRow(c:any):ContractItem{return{id:c.id,number:c.number,property:c.property?.title??'—',party:c.applicant?.name??'—',type:c.type,amount:money(Number(c.amount)),amountValue:Number(c.amount),commission:`${new Intl.NumberFormat('fa-IR').format(Number(c.commission)/1_000_000)} میلیون`,commissionValue:Number(c.commission),date:new Intl.DateTimeFormat('fa-IR').format(c.contractDate),status:c.status}}
export async function listContracts(){if(isDemoMode())return store;const rows=await prisma.contract.findMany({include:{property:true,applicant:true,agent:true},orderBy:{contractDate:'desc'}});return rows.map(mapRow)}
export async function createContract(input:Input){if(isDemoMode()){const item:ContractItem={id:`demo-contract-${Date.now()}`,number:input.number||`CNT-${Date.now()}`,property:'ملک دمو',party:'متقاضی دمو',type:input.type,amount:`${input.amount} میلیارد`,amountValue:input.amount*1_000_000_000,commission:`${input.commission} میلیون`,commissionValue:input.commission*1_000_000,date:new Intl.DateTimeFormat('fa-IR').format(new Date(input.contractDate)),status:input.status||'در انتظار امضا'};store=[item,...store];return item}let propertyId=input.propertyId,applicantId=input.applicantId,agentId=input.agentId;if(!propertyId){const p=await prisma.property.findFirst();if(!p)throw new Error('NO_PROPERTY');propertyId=p.id}if(!applicantId){const a=await prisma.applicant.findFirst();if(!a)throw new Error('NO_APPLICANT');applicantId=a.id}if(!agentId){const u=await prisma.user.findFirst();if(!u)throw new Error('NO_AGENT');agentId=u.id}const row=await prisma.contract.create({data:{number:input.number||`CNT-${Date.now()}`,type:input.type,amount:input.amount*1_000_000_000,commission:input.commission*1_000_000,contractDate:new Date(input.contractDate),status:input.status||'PENDING',notes:input.notes||null,propertyId,applicantId,agentId},include:{property:true,applicant:true,agent:true}});return mapRow(row)}
export async function deleteContract(id:string){if(isDemoMode()){store=store.filter(x=>x.id!==id);return}await prisma.contract.delete({where:{id}})}
