import { isDemoMode, prisma } from '@/lib/prisma';
import { agents, applicants, contracts, followups, properties } from '@/lib/demo-data';
import type { DataActor } from '@/lib/data-scope';
import { applicantScope, contractScope, followupScope, propertyScope } from '@/lib/data-scope';
import { scoreLead } from '@/lib/lead-scoring';

const PIPELINE = ['LEAD','CONTACTED','QUALIFIED','MATCHED','VISIT','NEGOTIATION','CONTRACT','WON'];
function parseFaNumber(value: string) { const fa='۰۱۲۳۴۵۶۷۸۹'; const ar='٠١٢٣٤٥٦٧٨٩'; const normalized=value.replace(/[۰-۹]/g,d=>String(fa.indexOf(d))).replace(/[٠-٩]/g,d=>String(ar.indexOf(d))).replace(/[^0-9.]/g,''); return Number(normalized)||0; }
function demoData() { const pipelineCounts=PIPELINE.map((stage,index)=>({stage,count:Math.max(0,applicants.length-index)})); return { kpis:{ properties:properties.length, activeProperties:properties.filter(x=>x.status==='فعال').length, negotiatingProperties:properties.filter(x=>x.status==='در مذاکره').length, applicants:applicants.length, urgentApplicants:applicants.filter(x=>x.urgency==='فوری').length, todayFollowups:followups.filter(x=>x.time.includes('امروز')).length, overdueFollowups:followups.filter(x=>x.priority==='عقب‌افتاده').length, visits:followups.filter(x=>x.type==='بازدید').length, negotiations:properties.filter(x=>x.status==='در مذاکره').length, contracts:contracts.length, completedContracts:contracts.filter(x=>x.status==='تکمیل شده').length, totalContractValue:contracts.reduce((sum,c)=>sum+parseFaNumber(String(c.amount)),0), totalCommission:contracts.reduce((sum,c)=>sum+parseFaNumber(String(c.commission)),0)/1000, conversionRate:applicants.length?Math.round((contracts.length/applicants.length)*100):0 }, pipeline:pipelineCounts, recentProperties:properties.slice(0,5), urgentFollowups:followups.slice(0,5).map(x=>({id:String(x.id),title:x.title,scheduledAt:new Date().toISOString(),priority:x.priority==='فوری'?4:2,assignee:{name:x.agent}})), agents:agents.map(x=>({name:x.name,contracts:x.deals,value:Number(x.value),commission:0,conversionRate:x.rate})), topLeads:[] }; }

export async function getDashboardAnalytics(actor?: DataActor) {
  if (isDemoMode) return demoData();
  const now=new Date(); const todayStart=new Date(now); todayStart.setHours(0,0,0,0); const todayEnd=new Date(now); todayEnd.setHours(23,59,59,999);
  const pWhere=actor?propertyScope(actor):undefined; const aWhere=actor?applicantScope(actor):undefined; const fWhere=actor?followupScope(actor):undefined; const cWhere=actor?contractScope(actor):undefined;
  const [propertyRows,applicantRows,followupRows,contractRows,recentProperties,leadCandidates]=await Promise.all([
    prisma.property.findMany({where:pWhere,select:{status:true}}),
    prisma.applicant.findMany({where:aWhere,select:{status:true,urgency:true,agentId:true,agent:{select:{name:true}}}}),
    prisma.followup.findMany({where:fWhere,select:{id:true,type:true,completed:true,scheduledAt:true,priority:true,title:true,assignee:{select:{name:true}}},orderBy:{scheduledAt:'asc'}}),
    prisma.contract.findMany({where:cWhere,include:{agent:{select:{id:true,name:true}}},orderBy:{contractDate:'desc'}}),
    prisma.property.findMany({where:pWhere,take:5,include:{owner:true,agent:true},orderBy:{createdAt:'desc'}}),
    prisma.applicant.findMany({where:aWhere,take:40,orderBy:{updatedAt:'desc'},select:{id:true,name:true,urgency:true,status:true,budgetMin:true,budgetMax:true,cities:true,districts:true,propertyTypes:true,minRooms:true,requiredFeatures:true,createdAt:true,agent:{select:{name:true}},followups:{select:{scheduledAt:true,completed:true},orderBy:{scheduledAt:'desc'},take:8},matchFeedback:{select:{verdict:true}},_count:{select:{contracts:true}}}}),
  ]);
  const pipeline=PIPELINE.map(stage=>({stage,count:applicantRows.filter(x=>x.status===stage).length}));
  const todayFollowups=followupRows.filter(x=>x.scheduledAt>=todayStart&&x.scheduledAt<=todayEnd); const overdueFollowups=followupRows.filter(x=>!x.completed&&x.scheduledAt<todayStart); const urgentFollowups=followupRows.filter(x=>!x.completed&&(x.priority>=3||x.scheduledAt<todayStart)).slice(0,5); const completedContracts=contractRows.filter(x=>['COMPLETED','SIGNED','WON','تکمیل شده','امضا شده'].includes(x.status)); const totalContractValue=contractRows.reduce((sum,x)=>sum+Number(x.amount),0); const totalCommission=contractRows.reduce((sum,x)=>sum+Number(x.commission),0);
  const agentMap=new Map<string,{name:string;contracts:number;value:number;commission:number;applicants:number}>();
  for(const applicant of applicantRows){const current=agentMap.get(applicant.agentId)||{name:applicant.agent.name,contracts:0,value:0,commission:0,applicants:0};current.applicants+=1;agentMap.set(applicant.agentId,current);} for(const contract of contractRows){const current=agentMap.get(contract.agentId)||{name:contract.agent.name,contracts:0,value:0,commission:0,applicants:0};current.contracts+=1;current.value+=Number(contract.amount);current.commission+=Number(contract.commission);agentMap.set(contract.agentId,current);}
  const topLeads=leadCandidates.map(x=>{const completed=x.followups.filter(f=>f.completed).sort((a,b)=>b.scheduledAt.getTime()-a.scheduledAt.getTime())[0]?.scheduledAt??null;const next=x.followups.filter(f=>!f.completed).sort((a,b)=>a.scheduledAt.getTime()-b.scheduledAt.getTime())[0]?.scheduledAt??null;const positive=x.matchFeedback.filter(f=>f.verdict==='POSITIVE').length,negative=x.matchFeedback.filter(f=>f.verdict==='NEGATIVE').length;return{id:x.id,name:x.name,agent:x.agent.name,status:x.status,...scoreLead({urgency:x.urgency,status:x.status,budgetMin:x.budgetMin==null?null:Number(x.budgetMin),budgetMax:x.budgetMax==null?null:Number(x.budgetMax),cities:x.cities,districts:x.districts,propertyTypes:x.propertyTypes,minRooms:x.minRooms,requiredFeatures:x.requiredFeatures,createdAt:x.createdAt,lastFollowupAt:completed,nextFollowupAt:next,positiveMatches:positive,negativeMatches:negative,contracts:x._count.contracts})}}).sort((a,b)=>b.score-a.score).slice(0,5);
  return { kpis:{properties:propertyRows.length,activeProperties:propertyRows.filter(x=>x.status==='ACTIVE').length,negotiatingProperties:propertyRows.filter(x=>x.status==='NEGOTIATING').length,applicants:applicantRows.length,urgentApplicants:applicantRows.filter(x=>x.urgency>=4).length,todayFollowups:todayFollowups.length,overdueFollowups:overdueFollowups.length,visits:followupRows.filter(x=>x.type==='VISIT').length,negotiations:applicantRows.filter(x=>x.status==='NEGOTIATION').length,contracts:contractRows.length,completedContracts:completedContracts.length,totalContractValue,totalCommission,conversionRate:applicantRows.length?Math.round((completedContracts.length/applicantRows.length)*100):0}, pipeline,recentProperties,urgentFollowups,agents:Array.from(agentMap.values()).map(x=>({...x,conversionRate:x.applicants?Math.round((x.contracts/x.applicants)*100):0})).sort((a,b)=>b.value-a.value),topLeads };
}
