import{prisma,isDemoMode}from'@/lib/prisma';import type{DataActor}from'@/lib/data-scope';
export async function getRecommendationAnalytics(actor:DataActor){if(isDemoMode)return{summary:{executions:0,evaluated:0,successes:0,successRate:0,contracts:0},actions:[],agents:[]};if(actor.role==='AGENT')throw new Error('FORBIDDEN');const actions=await prisma.$queryRaw<Array<any>>`
SELECT r."actionKey",COUNT(*)::int executions,COUNT(*) FILTER(WHERE r.success IS NOT NULL)::int evaluated,COUNT(*) FILTER(WHERE r.success=true)::int successes,COUNT(*) FILTER(WHERE r.outcome='CONTRACT')::int contracts,COUNT(*) FILTER(WHERE r.outcome='STAGE_ADVANCED')::int stage_advanced,COUNT(*) FILTER(WHERE r.outcome='POSITIVE_MATCH')::int positive_matches,COUNT(*) FILTER(WHERE r.outcome='FOLLOWUP_COMPLETED')::int followups
FROM "RecommendationOutcome" r WHERE r."agencyId"=${actor.agencyId} GROUP BY r."actionKey" ORDER BY successes DESC,executions DESC`;
const agents=await prisma.$queryRaw<Array<any>>`
SELECT u.id,u.name,COUNT(r.id)::int executions,COUNT(r.id) FILTER(WHERE r.success IS NOT NULL)::int evaluated,COUNT(r.id) FILTER(WHERE r.success=true)::int successes,COUNT(r.id) FILTER(WHERE r.outcome='CONTRACT')::int contracts
FROM "User" u LEFT JOIN "RecommendationOutcome" r ON r."userId"=u.id AND r."agencyId"=${actor.agencyId}
WHERE u."agencyId"=${actor.agencyId} AND u.role='AGENT' GROUP BY u.id,u.name ORDER BY successes DESC,executions DESC`;
const mappedActions=actions.map(x=>({...x,successRate:x.evaluated?Math.round(x.successes/x.evaluated*1000)/10:0}));const mappedAgents=agents.map(x=>({...x,successRate:x.evaluated?Math.round(x.successes/x.evaluated*1000)/10:0}));const summary=mappedActions.reduce((a,x)=>({executions:a.executions+x.executions,evaluated:a.evaluated+x.evaluated,successes:a.successes+x.successes,contracts:a.contracts+x.contracts}),{executions:0,evaluated:0,successes:0,contracts:0});return{summary:{...summary,successRate:summary.evaluated?Math.round(summary.successes/summary.evaluated*1000)/10:0},actions:mappedActions,agents:mappedAgents}}
