'use client';

import { useEffect, useState } from 'react';
import Link from 'next/link';
import { ArrowRight, Clock3, FileText, Phone, UserRoundSearch } from 'lucide-react';
import { Badge } from './ui';

const labels: Record<string,string> = { LEAD:'سرنخ', CONTACTED:'تماس اولیه', QUALIFIED:'نیازسنجی', MATCHED:'پیشنهاد ملک', VISIT:'بازدید', NEGOTIATION:'مذاکره', CONTRACT:'قرارداد', WON:'نهایی‌شده' };

type Applicant = { id:string; name:string; phone:string; requestType:string; budgetMin?:number|null; budgetMax?:number|null; urgency:number; status:string; notes?:string|null; agent?:{name:string}; contracts?:any[]; followups?:any[] };
type History = { id:string; fromStage?:string|null; toStage:string; changedAt:string; changedBy:{name:string} };

export default function ApplicantDetail({ id }:{id:string}){
  const [applicant,setApplicant]=useState<Applicant|null>(null); const [history,setHistory]=useState<History[]>([]); const [error,setError]=useState('');
  useEffect(()=>{Promise.all([fetch(`/api/applicants/${id}`).then(r=>r.json()),fetch(`/api/applicants/${id}/history`).then(r=>r.json())]).then(([a,h])=>{if(a.data)setApplicant(a.data);else setError(a.error||'پرونده پیدا نشد');if(Array.isArray(h.data))setHistory(h.data)}).catch(()=>setError('دریافت پرونده انجام نشد'));},[id]);
  if(error)return <div className="card p-8 text-center text-red-700">{error}</div>; if(!applicant)return <div className="card p-8 text-center text-slate-500">در حال دریافت پرونده...</div>;
  return <div className="space-y-4"><div className="flex items-center gap-3"><Link href="/pipeline" className="btn-secondary"><ArrowRight size={16}/>Pipeline</Link><div><h1 className="text-2xl font-bold">{applicant.name}</h1><p className="text-sm text-slate-500">پرونده متقاضی · {applicant.agent?.name||'بدون مشاور'}</p></div></div>
    <div className="grid gap-4 md:grid-cols-4"><div className="card p-4"><Phone className="mb-2 text-brand-600"/><p className="text-xs text-slate-500">تماس</p><b>{applicant.phone}</b></div><div className="card p-4"><UserRoundSearch className="mb-2 text-brand-600"/><p className="text-xs text-slate-500">مرحله فعلی</p><Badge tone="green">{labels[applicant.status]||applicant.status}</Badge></div><div className="card p-4"><FileText className="mb-2 text-brand-600"/><p className="text-xs text-slate-500">نوع درخواست</p><b>{applicant.requestType}</b></div><div className="card p-4"><Clock3 className="mb-2 text-brand-600"/><p className="text-xs text-slate-500">بودجه</p><b>{applicant.budgetMax?`تا ${Number(applicant.budgetMax).toLocaleString('fa-IR')} میلیارد`:'ثبت نشده'}</b></div></div>
    <div className="grid gap-4 xl:grid-cols-3"><section className="card p-5 xl:col-span-2"><h2 className="font-bold">Timeline مسیر فروش</h2><p className="mt-1 text-xs text-slate-500">تمام تغییرات Stage به‌ترتیب زمانی ثبت می‌شوند.</p><div className="mt-5 space-y-4">{history.map((h,index)=><div key={h.id} className="relative flex gap-4"><div className="flex flex-col items-center"><span className="grid h-9 w-9 place-items-center rounded-full bg-brand-100 text-xs font-bold text-brand-700">{history.length-index}</span>{index<history.length-1&&<span className="h-full w-px bg-slate-200"/>}</div><div className="pb-5"><b className="text-sm">{h.fromStage?`${labels[h.fromStage]||h.fromStage} ← ${labels[h.toStage]||h.toStage}`:`شروع در ${labels[h.toStage]||h.toStage}`}</b><p className="mt-1 text-xs text-slate-500">{new Intl.DateTimeFormat('fa-IR-u-ca-persian',{dateStyle:'medium',timeStyle:'short'}).format(new Date(h.changedAt))} · {h.changedBy.name}</p></div></div>)}{!history.length&&<p className="text-sm text-slate-500">هنوز تاریخچه‌ای ثبت نشده است.</p>}</div></section>
    <aside className="space-y-4"><div className="card p-5"><h3 className="font-bold">خلاصه پرونده</h3><div className="mt-4 space-y-3 text-sm"><div className="flex justify-between"><span className="text-slate-500">پیگیری‌ها</span><b>{applicant.followups?.length||0}</b></div><div className="flex justify-between"><span className="text-slate-500">قراردادها</span><b>{applicant.contracts?.length||0}</b></div><div className="flex justify-between"><span className="text-slate-500">فوریت</span><b>{applicant.urgency}</b></div></div></div>{applicant.notes&&<div className="card p-5"><h3 className="font-bold">یادداشت</h3><p className="mt-3 text-sm leading-7 text-slate-600">{applicant.notes}</p></div>}</aside></div></div>;
}
