'use client';

import {Building2,Users,PhoneCall,CalendarDays,FileSignature,TrendingUp,ArrowLeft,Clock,CheckCircle2,ArrowUpLeft,Target,MoreHorizontal,Sparkles} from 'lucide-react';
import Link from 'next/link';
import {ResponsiveContainer,AreaChart,Area,XAxis,YAxis,CartesianGrid,Tooltip,PieChart,Pie,Cell} from 'recharts';
import {agents,followups,properties} from '@/lib/demo-data';
import {Badge} from './ui';

const monthly=[{m:'فروردین',v:12},{m:'اردیبهشت',v:18},{m:'خرداد',v:15},{m:'تیر',v:24},{m:'مرداد',v:20},{m:'شهریور',v:29},{m:'مهر',v:33},{m:'آبان',v:28},{m:'آذر',v:41}];
const pie=[{name:'فعال',value:62,c:'#2f8b75'},{name:'در مذاکره',value:21,c:'#d79a2b'},{name:'فروخته',value:17,c:'#a8b5b0'}];
const cards=[
  {title:'کل ملک‌ها',value:'۱۲۸',detail:'۱۲٪ نسبت به ماه قبل',icon:Building2,tone:'brand'},
  {title:'ملک‌های فعال',value:'۷۹',detail:'۸ فایل جدید این هفته',icon:TrendingUp,tone:'brand'},
  {title:'متقاضی فعال',value:'۵۶',detail:'۱۱ متقاضی با اولویت بالا',icon:Users,tone:'accent'},
  {title:'پیگیری امروز',value:'۱۴',detail:'۳ مورد هنوز باقی مانده',icon:PhoneCall,tone:'accent'},
] as const;

export default function Dashboard(){
 return <div className="space-y-5">
  <section className="relative overflow-hidden rounded-3xl bg-brand-950 p-6 text-white shadow-float md:p-8">
   <div className="absolute -left-16 -top-20 h-64 w-64 rounded-full bg-brand-500/20 blur-3xl"/><div className="absolute bottom-0 right-1/3 h-32 w-32 rounded-full bg-accent-500/10 blur-2xl"/>
   <div className="relative flex flex-col gap-6 xl:flex-row xl:items-end xl:justify-between"><div><div className="mb-4 inline-flex items-center gap-2 rounded-full border border-white/10 bg-white/10 px-3 py-1.5 text-xs text-brand-100"><Sparkles size={14}/>نمای کلی کسب‌وکار</div><p className="text-xs text-brand-200">چهارشنبه، ۲۱ آذر ۱۴۰۳</p><h1 className="mt-2 text-2xl font-extrabold tracking-tight md:text-3xl">صبح بخیر مهدی؛ وضعیت آژانس رو به رشد است.</h1><p className="mt-2 max-w-2xl text-sm leading-7 text-brand-100">امروز ۱۴ پیگیری و ۲ جلسه دارید. ارزش معاملات این ماه نسبت به ماه قبل ۱۸٪ افزایش داشته است.</p></div><div className="flex flex-wrap gap-3"><Link href="/followups" className="btn border border-white/15 bg-white/10 text-white hover:bg-white/15"><CalendarDays size={17}/>برنامه امروز</Link><Link href="/properties" className="btn bg-white text-brand-950 hover:-translate-y-0.5"><Building2 size={17}/>ثبت ملک جدید</Link></div></div>
   <div className="relative mt-7 grid gap-3 sm:grid-cols-3"><div className="rounded-2xl border border-white/10 bg-white/10 p-4 backdrop-blur"><p className="text-xs text-brand-200">فروش این ماه</p><div className="mt-2 flex items-end gap-2"><b className="text-2xl">۴۱.۲</b><span className="pb-1 text-xs text-brand-200">میلیارد تومان</span></div></div><div className="rounded-2xl border border-white/10 bg-white/10 p-4 backdrop-blur"><p className="text-xs text-brand-200">قراردادهای بسته‌شده</p><div className="mt-2 flex items-center gap-2"><b className="text-2xl">۹</b><span className="badge bg-brand-500/20 text-brand-100">+۳ این ماه</span></div></div><div className="rounded-2xl border border-white/10 bg-white/10 p-4 backdrop-blur"><p className="text-xs text-brand-200">نرخ تبدیل متقاضی</p><div className="mt-2 flex items-center gap-2"><b className="text-2xl">۲۴٪</b><ArrowUpLeft size={17} className="text-brand-300"/></div></div></div>
  </section>

  <section className="grid gap-4 sm:grid-cols-2 xl:grid-cols-4">{cards.map(({title,value,detail,icon:Icon,tone})=><div className="card group p-5 transition duration-200 hover:-translate-y-1" key={title}><div className="flex items-start justify-between"><div><p className="text-sm font-medium text-ink-500">{title}</p><b className="mt-2 block text-3xl tracking-tight text-ink-900">{value}</b></div><span className={`grid h-11 w-11 place-items-center rounded-2xl ${tone==='brand'?'bg-brand-50 text-brand-700':'bg-accent-50 text-accent-600'}`}><Icon size={20}/></span></div><div className="mt-4 flex items-center gap-2 border-t border-ink-100 pt-3 text-xs text-ink-500"><TrendingUp size={14} className="text-brand-600"/>{detail}</div></div>)}</section>

  <section className="grid gap-4 lg:grid-cols-3"><div className="card p-5 md:p-6 lg:col-span-2"><div className="mb-6 flex items-start justify-between gap-4"><div><h2 className="font-extrabold text-ink-900">روند ارزش معاملات</h2><p className="mt-1 text-xs text-ink-500">میلیارد تومان · ۹ ماه گذشته</p></div><div className="text-left"><b className="text-lg text-brand-700">۲۴۸.۵ میلیارد</b><p className="mt-1 text-xs text-brand-600">۱۸٪ رشد</p></div></div><div className="h-72" dir="ltr"><ResponsiveContainer><AreaChart data={monthly}><defs><linearGradient id="dealValue" x1="0" y1="0" x2="0" y2="1"><stop offset="0" stopColor="#2f8b75" stopOpacity=".28"/><stop offset="1" stopColor="#2f8b75" stopOpacity="0"/></linearGradient></defs><CartesianGrid stroke="#edf1ef" strokeDasharray="4 5" vertical={false}/><XAxis dataKey="m" axisLine={false} tickLine={false} tick={{fontSize:10,fill:'#60716b'}}/><YAxis axisLine={false} tickLine={false} tick={{fontSize:10,fill:'#60716b'}}/><Tooltip contentStyle={{borderRadius:16,border:'1px solid #edf1ef',boxShadow:'0 10px 35px rgba(23,33,30,.08)'}}/><Area type="monotone" dataKey="v" stroke="#236f5e" strokeWidth={3} fill="url(#dealValue)"/></AreaChart></ResponsiveContainer></div></div>
   <div className="card p-5 md:p-6"><div className="flex items-start justify-between"><div><h2 className="font-extrabold text-ink-900">سبد ملک‌ها</h2><p className="mt-1 text-xs text-ink-500">پراکندگی وضعیت ۱۲۸ فایل</p></div><button className="rounded-xl p-2 text-ink-500 hover:bg-ink-50"><MoreHorizontal size={18}/></button></div><div className="relative h-48"><ResponsiveContainer><PieChart><Pie data={pie} dataKey="value" innerRadius={57} outerRadius={78} paddingAngle={5} stroke="none">{pie.map(x=><Cell key={x.name} fill={x.c}/>)}</Pie><Tooltip/></PieChart></ResponsiveContainer><div className="pointer-events-none absolute inset-0 grid place-items-center"><div className="text-center"><b className="block text-xl text-ink-900">۱۲۸</b><span className="text-[10px] text-ink-500">کل فایل‌ها</span></div></div></div><div className="space-y-3">{pie.map(x=><div className="flex items-center text-sm text-ink-600" key={x.name}><i className="ml-2.5 h-2.5 w-2.5 rounded-full" style={{background:x.c}}/>{x.name}<b className="mr-auto text-ink-900">{x.value}٪</b></div>)}</div></div></section>

  <section className="grid gap-4 xl:grid-cols-5"><div className="card overflow-hidden xl:col-span-3"><div className="flex items-center justify-between p-5 md:px-6"><div><h2 className="font-extrabold text-ink-900">فایل‌های تازه</h2><p className="mt-1 text-xs text-ink-500">آخرین ملک‌های اضافه‌شده به سبد</p></div><Link href="/properties" className="flex items-center gap-1 text-xs font-bold text-brand-700">همه ملک‌ها <ArrowLeft size={14}/></Link></div><div className="table-wrap rounded-none border-x-0 border-b-0"><table className="data-table"><tbody>{properties.slice(0,4).map(p=><tr key={p.id}><td><div className="flex items-center gap-3"><img src={p.image} alt="" className="h-12 w-16 rounded-2xl object-cover"/><div><b className="text-sm text-ink-900">{p.title}</b><small className="mt-1 block text-ink-500">{p.code} · {p.area} متر</small></div></div></td><td>{p.deal}</td><td className="font-semibold text-ink-900">{p.price} میلیارد</td><td><Badge tone={p.status==='فعال'?'green':'amber'}>{p.status}</Badge></td></tr>)}</tbody></table></div></div>
   <div className="card p-5 md:p-6 xl:col-span-2"><div className="mb-5 flex items-start justify-between"><div><h2 className="font-extrabold text-ink-900">اقدام‌های امروز</h2><p className="mt-1 text-xs text-ink-500">مواردی که نیاز به توجه دارند</p></div><span className="badge bg-accent-50 text-accent-600">۳ فوری</span></div><div className="space-y-3">{followups.slice(0,4).map(f=><div key={f.id} className="group flex gap-3 rounded-2xl border border-ink-100 p-3.5 transition hover:border-brand-100 hover:bg-brand-50/40"><div className={`mt-0.5 grid h-9 w-9 shrink-0 place-items-center rounded-xl ${f.priority==='فوری'?'bg-accent-50 text-accent-600':'bg-brand-50 text-brand-700'}`}>{f.priority==='فوری'?<Clock size={17}/>:<CheckCircle2 size={17}/>}</div><div className="min-w-0"><b className="block truncate text-sm text-ink-900">{f.title}</b><p className="mt-1 text-xs text-ink-500">{f.time} · {f.agent}</p></div><ArrowLeft size={15} className="mr-auto mt-2 text-ink-300 opacity-0 transition group-hover:opacity-100"/></div>)}</div><Link href="/followups" className="btn-secondary mt-4 w-full">مشاهده برنامه کامل</Link></div></section>

  <section className="card p-5 md:p-6"><div className="mb-6 flex flex-wrap items-start justify-between gap-3"><div><h2 className="font-extrabold text-ink-900">عملکرد تیم فروش</h2><p className="mt-1 text-xs text-ink-500">مقایسه تحقق هدف مشاوران در ماه جاری</p></div><div className="flex items-center gap-2 text-xs text-ink-500"><Target size={16} className="text-brand-600"/>هدف ماهانه: ۵۰ میلیارد</div></div><div className="grid gap-6 md:grid-cols-2 xl:grid-cols-4">{agents.map(a=><div key={a.name} className="rounded-2xl border border-ink-100 p-4"><div className="flex items-center gap-3"><div className="grid h-11 w-11 place-items-center rounded-2xl bg-brand-100 font-extrabold text-brand-800">{a.name[0]}</div><div><b className="text-sm text-ink-900">{a.name}</b><p className="mt-1 text-xs text-ink-500">{a.deals} قرارداد · {a.value} میلیارد</p></div></div><div className="mt-4 flex justify-between text-[11px]"><span className="text-ink-500">تحقق هدف</span><b className="text-brand-700">{a.rate}٪</b></div><div className="mt-2 h-2 overflow-hidden rounded-full bg-ink-100"><div className="h-full rounded-full bg-brand-600" style={{width:`${a.rate}%`}}/></div></div>)}</div></section>
 </div>;
}
