'use client';
import { useRef,useState } from 'react';
import { ArrowDown,ArrowUp,FileText,ImagePlus,Link as LinkIcon,Loader2,Star,Trash2,UploadCloud } from 'lucide-react';
import type { PropertyDocument } from '@/lib/types';
import { formatPersianDateTime } from '@/lib/date';

type Kind='image'|'document';
function keyFromUrl(url:string){const marker='/api/storage/file?key=';return url.startsWith(marker)?decodeURIComponent(url.slice(marker.length)):null}
export default function PropertyMediaManager({propertyId,initialImages=[],initialDocuments=[]}:{propertyId:string|number;initialImages?:string[];initialDocuments?:PropertyDocument[]}){
  const[images,setImages]=useState(initialImages),[documents,setDocuments]=useState(initialDocuments),[saving,setSaving]=useState(false),[uploading,setUploading]=useState(false),[error,setError]=useState('');
  const imageInput=useRef<HTMLInputElement>(null),docInput=useRef<HTMLInputElement>(null);
  async function save(nextImages=images,nextDocuments=documents){setSaving(true);setError('');try{const r=await fetch(`/api/properties/${propertyId}/media`,{method:'PATCH',headers:{'Content-Type':'application/json'},body:JSON.stringify({images:nextImages,documents:nextDocuments})});const j=await r.json();if(!r.ok)throw new Error(j.error||'ذخیره انجام نشد');setImages(j.data.images||[]);setDocuments(j.data.documents||[])}catch(e){setError(e instanceof Error?e.message:'خطا')}finally{setSaving(false)}}
  async function uploadOne(file:File,kind:Kind){const sign=await fetch('/api/storage/sign',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({propertyId:String(propertyId),kind,name:file.name,type:file.type,size:file.size})});const s=await sign.json();if(!sign.ok)throw new Error(s.error||'ساخت لینک آپلود انجام نشد');const put=await fetch(s.uploadUrl,{method:'PUT',headers:{'Content-Type':file.type},body:file});if(!put.ok)throw new Error('آپلود فایل در Storage انجام نشد.');return String(s.fileUrl)}
  async function uploadFiles(files:FileList|File[],kind:Kind){const list=Array.from(files);if(!list.length)return;setUploading(true);setError('');try{if(kind==='image'){const urls:string[]=[];for(const file of list)urls.push(await uploadOne(file,'image'));await save([...images,...urls],documents)}else{const next=[...documents];for(const file of list){const url=await uploadOne(file,'document');next.push({id:crypto.randomUUID(),name:file.name,url,type:file.type,size:file.size,createdAt:new Date().toISOString()})}await save(images,next)}}catch(e){setError(e instanceof Error?e.message:'آپلود انجام نشد')}finally{setUploading(false)}}
  function move(index:number,dir:-1|1){const target=index+dir;if(target<0||target>=images.length)return;const next=[...images];[next[index],next[target]]=[next[target],next[index]];save(next,documents)}
  function primary(index:number){save([images[index],...images.filter((_,i)=>i!==index)],documents)}
  async function removeStored(url:string){const key=keyFromUrl(url);if(!key)return;const r=await fetch(`/api/storage/file?key=${encodeURIComponent(key)}`,{method:'DELETE'});if(!r.ok){const j=await r.json().catch(()=>({}));throw new Error(j.error||'حذف فایل از Storage انجام نشد')}}
  async function removeImage(index:number){setSaving(true);setError('');try{await removeStored(images[index]);await save(images.filter((_,i)=>i!==index),documents)}catch(e){setError(e instanceof Error?e.message:'حذف انجام نشد');setSaving(false)}}
  async function removeDocument(id:string){const item=documents.find(x=>x.id===id);if(!item)return;setSaving(true);setError('');try{await removeStored(item.url);await save(images,documents.filter(x=>x.id!==id))}catch(e){setError(e instanceof Error?e.message:'حذف انجام نشد');setSaving(false)}}
  const busy=saving||uploading;
  return <section className="card p-6"><div><h2 className="font-bold">تصاویر و مدارک ملک</h2><p className="mt-1 text-xs text-slate-500">فایل‌ها مستقیم و امن در Object Storage ذخیره می‌شوند. تصویر اول، تصویر اصلی ملک است.</p></div>
    <div className="mt-5"><div onDragOver={e=>e.preventDefault()} onDrop={e=>{e.preventDefault();uploadFiles(e.dataTransfer.files,'image')}} onClick={()=>imageInput.current?.click()} className="cursor-pointer rounded-2xl border-2 border-dashed border-slate-200 p-7 text-center hover:border-brand-300 hover:bg-brand-50/30"><UploadCloud className="mx-auto text-brand-600"/><b className="mt-2 block text-sm">تصاویر را اینجا رها کنید یا انتخاب کنید</b><p className="mt-1 text-xs text-slate-500">JPG / PNG / WEBP · حداکثر ۱۰MB برای هر تصویر</p><input ref={imageInput} hidden type="file" multiple accept="image/jpeg,image/png,image/webp" onChange={e=>e.target.files&&uploadFiles(e.target.files,'image')}/></div>
      <div className="mt-4 grid gap-3 sm:grid-cols-2 lg:grid-cols-3">{images.map((url,i)=><div key={`${url}-${i}`} className="overflow-hidden rounded-xl border bg-slate-50"><img src={url} alt={`تصویر ${i+1}`} className="h-36 w-full object-cover"/><div className="flex items-center gap-1 p-2">{i===0?<span className="badge bg-amber-50 text-amber-700"><Star size={12}/>اصلی</span>:<button className="rounded-lg p-2 hover:bg-white" title="تصویر اصلی" onClick={()=>primary(i)}><Star size={15}/></button>}<button className="rounded-lg p-2 hover:bg-white" onClick={()=>move(i,-1)}><ArrowUp size={15}/></button><button className="rounded-lg p-2 hover:bg-white" onClick={()=>move(i,1)}><ArrowDown size={15}/></button><button disabled={busy} className="mr-auto rounded-lg p-2 text-red-600 hover:bg-red-50" onClick={()=>removeImage(i)}><Trash2 size={15}/></button></div></div>)}</div>
    </div>
    <div className="mt-7 border-t pt-5"><div className="flex items-center justify-between"><div><h3 className="font-bold">مدارک</h3><p className="mt-1 text-xs text-slate-500">PDF یا تصویر سند · حداکثر ۲۰MB</p></div><button disabled={busy} className="btn-secondary" onClick={()=>docInput.current?.click()}>{uploading?<Loader2 className="animate-spin" size={16}/>:<ImagePlus size={16}/>}آپلود مدرک</button><input ref={docInput} hidden type="file" multiple accept="application/pdf,image/jpeg,image/png,image/webp" onChange={e=>e.target.files&&uploadFiles(e.target.files,'document')}/></div>
      <div className="mt-4 space-y-2">{documents.map(d=><div key={d.id} className="flex items-center gap-3 rounded-xl border p-3"><FileText className="text-brand-600" size={18}/><div className="min-w-0 flex-1"><b className="block truncate text-sm">{d.name}</b><p className="mt-1 text-xs text-slate-500">{d.createdAt?formatPersianDateTime(d.createdAt):'تاریخ ثبت نشده'}{d.size?` · ${(d.size/1024/1024).toLocaleString('fa-IR',{maximumFractionDigits:1})} MB`:''}</p></div><a href={d.url} target="_blank" rel="noreferrer" className="rounded-lg p-2 hover:bg-slate-50"><LinkIcon size={16}/></a><button disabled={busy} className="rounded-lg p-2 text-red-600 hover:bg-red-50" onClick={()=>removeDocument(d.id)}><Trash2 size={16}/></button></div>)}{!documents.length&&<p className="text-sm text-slate-400">مدرکی ثبت نشده است.</p>}</div>
    </div>{busy&&<p className="mt-4 flex items-center gap-2 text-sm text-brand-700"><Loader2 className="animate-spin" size={16}/>در حال پردازش فایل‌ها...</p>}{error&&<p className="mt-4 text-sm text-red-600">{error}</p>}</section>
}
