'use client';

import Link from 'next/link';
import { useEffect, useMemo, useState } from 'react';
import { BarChart3, Clock3, FileWarning, WalletCards } from 'lucide-react';
import { Bar, BarChart, CartesianGrid, Line, LineChart, ResponsiveContainer, Tooltip, XAxis, YAxis } from 'recharts';
import { Header } from './properties-view';

const labels: Record<string,string> = { LEAD:'سرنخ', CONTACTED:'تماس', QUALIFIED:'نیازسنجی', MATCHED:'پیشنهاد', VISIT:'بازدید', NEGOTIATION:'مذاکره', CONTRACT:'قرارداد', WON:'نهایی' };
type ReportData = { kpis:{avgDaysToContract:number;staleProperties:number;totalValue:number;totalCommission:number}; funnel:{stage:string;count:number;shareOfPipeline:number}[]; monthly:{month:string;value:number;commission:number;contracts:number}[]; agents:{name:string;applicants:number;contracts:number;conversionRate:number;value:number;commission:number}[]; staleProperties:{id:string;title:string;code:string;agent:string;lastActivityAt:string}[]; pipelineHistory:{transitions:{transition:string;count:number}[];averageDaysByStage:{stage:string;days:number}[]} };
function fa(value:number){return value.toLocaleString('fa-IR',{maximumFractionDigits:1})}

export default function ReportsView(){
  const [data,setData]=useState<ReportData|null>(null); const [from,setFrom]=useState(''); const [to,setTo]=useState(''); const [error,setError]=useState('');
  async function load(nextFrom=from,nextTo=to){setError('');const params=new URLSearchParams();if(nextFrom)params.set('from',nextFrom);if(nextTo)params.set('to',nextTo);try{const r=await fetch(`/api/reports?${params}`);const j=await r.json();if(!r.ok)throw new Error(j.error||'خطا');setData(j)}catch(e){setError(e instanceof Error?e.message:'خطا در دریافت گزارش')}}
  useEffect(()=>{load('','')},[]);
  const monthly=useMemo(()=>data?.monthly.map(x=>({...x,label:new Intl.DateTimeFormat('fa-IR-u-ca-persian',{month:'short',year:'2-digit'}).format(new Date(`${x.month}-01`))}))||[],[data]);
  const stageTiming=useMemo(()=>data?.pipelineHistory.averageDaysByStage.map(x=>({...x,label:labels[x.stage]||x.stage}))||[],[data]);
  const transitions=useMemo(()=>data?.pipelineHistory.transitions.map(x=>{const [a,b]=x.transition.split('->');return {...x,label:`${labels[a]||a} ← ${labels[b]||b}`}})||[],[data]);
  if(!data&&!error)return <div className="card p-10 text-center text-sm text-slate-500">در حال آماده‌سازی گزارش‌ها...</div>;
  return <><Header title="گزارش‌های مدیریتی" sub="تحلیل عملکرد فروش، زمان مراحل Pipeline، کمیسیون و فایل‌های نیازمند پیگیری" />
    <div className="card mb-4 flex flex-wrap items-end gap-3 p-4"><div><label className="label">از تاریخ</label><input type="date" value={from} onChange={e=>setFrom(e.target.value)} className="input"/></div><div><label className="label">تا تاریخ</label><input type="date" value={to} onChange={e=>setTo(e.target.value)} className="input"/></div><button onClick={()=>load()} className="btn-primary">اعمال فیلتر</button><button onClick={()=>{setFrom('');setTo('');load('','')}} className="btn-secondary">پاک‌کردن</button></div>
    {error&&<div className="mb-4 rounded-xl bg-red-50 p-3 text-sm text-red-700">{error}</div>}
    {data&&<><div className="grid gap-4 sm:grid-cols-2 xl:grid-cols-4"><div className="card p-5"><Clock3 className="mb-3 text-brand-600"/><p className="text-sm text-slate-500">میانگین زمان تا قرارداد</p><b className="mt-2 block text-2xl">{fa(data.kpis.avgDaysToContract)} روز</b></div><div className="card p-5"><FileWarning className="mb-3 text-amber-600"/><p className="text-sm text-slate-500">فایل بدون پیگیری ۱۴روزه</p><b className="mt-2 block text-2xl">{fa(data.kpis.staleProperties)}</b></div><div className="card p-5"><BarChart3 className="mb-3 text-brand-600"/><p className="text-sm text-slate-500">ارزش قراردادها</p><b className="mt-2 block text-2xl">{fa(data.kpis.totalValue)}</b></div><div className="card p-5"><WalletCards className="mb-3 text-brand-600"/><p className="text-sm text-slate-500">کمیسیون</p><b className="mt-2 block text-2xl">{fa(data.kpis.totalCommission)}</b></div></div>
      <div className="mt-4 grid gap-4 xl:grid-cols-2"><div className="card p-5"><h2 className="font-bold">میانگین زمان ماندن در هر Stage</h2><p className="mt-1 text-xs text-slate-500">Stage با زمان بالاتر، کاندید گلوگاه فروش است.</p><div className="mt-4 h-72" dir="ltr"><ResponsiveContainer><BarChart data={stageTiming}><CartesianGrid strokeDasharray="3 3" vertical={false}/><XAxis dataKey="label" tick={{fontSize:10}}/><YAxis/><Tooltip/><Bar dataKey="days"/></BarChart></ResponsiveContainer></div></div><div className="card p-5"><h2 className="font-bold">Transitionهای واقعی Pipeline</h2><p className="mt-1 text-xs text-slate-500">تعداد جابه‌جایی‌های ثبت‌شده بین مراحل.</p><div className="mt-4 h-72" dir="ltr"><ResponsiveContainer><BarChart data={transitions}><CartesianGrid strokeDasharray="3 3" vertical={false}/><XAxis dataKey="label" tick={{fontSize:9}}/><YAxis/><Tooltip/><Bar dataKey="count"/></BarChart></ResponsiveContainer></div></div></div>
      <div className="mt-4 grid gap-4 xl:grid-cols-2"><div className="card p-5"><h2 className="font-bold">توزیع فعلی Pipeline</h2><div className="mt-4 h-72" dir="ltr"><ResponsiveContainer><BarChart data={data.funnel.map(x=>({...x,label:labels[x.stage]||x.stage}))}><CartesianGrid strokeDasharray="3 3" vertical={false}/><XAxis dataKey="label" tick={{fontSize:10}}/><YAxis/><Tooltip/><Bar dataKey="count"/></BarChart></ResponsiveContainer></div></div><div className="card p-5"><h2 className="font-bold">روند ماهانه ارزش قراردادها</h2><div className="mt-4 h-72" dir="ltr"><ResponsiveContainer><LineChart data={monthly}><CartesianGrid strokeDasharray="3 3" vertical={false}/><XAxis dataKey="label" tick={{fontSize:10}}/><YAxis/><Tooltip/><Line type="monotone" dataKey="value" strokeWidth={3}/></LineChart></ResponsiveContainer></div></div></div>
      <div className="mt-4 card"><div className="p-5"><h2 className="font-bold">عملکرد مشاوران</h2></div><div className="table-wrap"><table className="data-table"><thead><tr><th>مشاور</th><th>متقاضی</th><th>قرارداد</th><th>نرخ قرارداد/متقاضی</th><th>ارزش</th><th>کمیسیون</th></tr></thead><tbody>{data.agents.map(a=><tr key={a.name}><td><b>{a.name}</b></td><td>{fa(a.applicants)}</td><td>{fa(a.contracts)}</td><td>{fa(a.conversionRate)}٪</td><td>{fa(a.value)}</td><td>{fa(a.commission)}</td></tr>)}</tbody></table></div></div>
      <div className="mt-4 card"><div className="p-5"><h2 className="font-bold">فایل‌های نیازمند پیگیری</h2><p className="mt-1 text-xs text-slate-500">ملک‌هایی که بیش از ۱۴ روز از آخرین فعالیتشان گذشته است.</p></div><div className="divide-y">{data.staleProperties.map(p=><div key={p.id} className="flex flex-wrap items-center gap-3 p-4 text-sm"><div><b>{p.title}</b><p className="text-xs text-slate-500">{p.code} · {p.agent}</p></div><span className="mr-auto text-xs text-slate-500">{new Intl.DateTimeFormat('fa-IR-u-ca-persian').format(new Date(p.lastActivityAt))}</span><Link href={`/properties/${p.id}`} className="btn-secondary">باز کردن پرونده</Link></div>)}{!data.staleProperties.length&&<div className="p-8 text-center text-sm text-slate-500">فایل بدون پیگیری طولانی وجود ندارد.</div>}</div></div></>}
  </>;
}
