'use client';
import { useEffect,useState } from 'react';
import { KeyRound, LogOut, RefreshCw, ShieldCheck, ShieldX } from 'lucide-react';
import { formatPersianDateTime } from '@/lib/date';

type EventRow={id:string;email:string;success:boolean;reason?:string|null;ip?:string|null;userAgent?:string|null;createdAt:string};
type UserRow={id:string;name:string;email:string};
type TwoFactorStatus={enabled:boolean;recoveryCodesRemaining:number};
const reasonLabels:Record<string,string>={LOGIN_SUCCESS:'ورود موفق',LOGIN_SUCCESS_2FA:'ورود موفق با 2FA',INVALID_PASSWORD:'رمز اشتباه',INVALID_TWO_FACTOR:'کد دومرحله‌ای نامعتبر',LOCKED_AFTER_FAILURES:'قفل موقت پس از چند خطا',ACCOUNT_LOCKED:'تلاش هنگام قفل بودن حساب',INACTIVE_ACCOUNT:'حساب غیرفعال',UNKNOWN_EMAIL:'ایمیل ناشناخته',SESSIONS_REVOKED_SELF:'خروج از همه دستگاه‌ها',SESSIONS_REVOKED_BY_MANAGER:'خروج اجباری توسط مدیر'};

export default function SecurityCenter(){
  const[events,setEvents]=useState<EventRow[]>([]),[users,setUsers]=useState<UserRow[]>([]),[selected,setSelected]=useState(''),[currentUserId,setCurrentUserId]=useState(''),[error,setError]=useState(''),[busy,setBusy]=useState(false);
  const[twoFactor,setTwoFactor]=useState<TwoFactorStatus>({enabled:false,recoveryCodesRemaining:0}),[qr,setQr]=useState(''),[secret,setSecret]=useState(''),[code,setCode]=useState(''),[recoveryCodes,setRecoveryCodes]=useState<string[]>([]);
  async function load(userId=selected){const q=userId?`?userId=${userId}`:'';const r=await fetch(`/api/security/account${q}`),j=await r.json();if(!r.ok)throw new Error(j.error||'خطا');setEvents(j.data||[]);setUsers(j.users||[]);setCurrentUserId(j.currentUserId||'')}
  async function load2fa(){const r=await fetch('/api/security/2fa'),j=await r.json();if(r.ok)setTwoFactor(j)}
  useEffect(()=>{load().catch(e=>setError(e.message));load2fa().catch(()=>{})},[]);
  async function revoke(){setBusy(true);setError('');try{const target=selected||currentUserId;const r=await fetch('/api/security/account',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({userId:target})}),j=await r.json();if(!r.ok)throw new Error(j.error||'انجام نشد');if(target===currentUserId)window.location.href='/login';else await load(target)}catch(e){setError(e instanceof Error?e.message:'خطا')}finally{setBusy(false)}}
  async function begin2fa(){setBusy(true);setError('');try{const r=await fetch('/api/security/2fa',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({action:'begin'})}),j=await r.json();if(!r.ok)throw new Error(j.error||'شروع فعال‌سازی انجام نشد');setQr(j.qr);setSecret(j.secret);setRecoveryCodes([])}catch(e){setError(e instanceof Error?e.message:'خطا')}finally{setBusy(false)}}
  async function confirm2fa(){setBusy(true);setError('');try{const r=await fetch('/api/security/2fa',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({action:'confirm',code})}),j=await r.json();if(!r.ok)throw new Error(j.error||'کد معتبر نیست');setTwoFactor({enabled:true,recoveryCodesRemaining:j.recoveryCodes?.length||0});setRecoveryCodes(j.recoveryCodes||[]);setQr('');setSecret('');setCode('')}catch(e){setError(e instanceof Error?e.message:'خطا')}finally{setBusy(false)}}
  async function disable2fa(){setBusy(true);setError('');try{const r=await fetch('/api/security/2fa',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({action:'disable',code})}),j=await r.json();if(!r.ok)throw new Error(j.error||'غیرفعال‌سازی انجام نشد');setTwoFactor({enabled:false,recoveryCodesRemaining:0});setRecoveryCodes([]);setCode('')}catch(e){setError(e instanceof Error?e.message:'خطا')}finally{setBusy(false)}}
  return <div><div className="flex flex-wrap items-center gap-3"><div><h1 className="text-2xl font-bold">امنیت حساب</h1><p className="mt-1 text-sm text-slate-500">ورودها، 2FA و مدیریت Sessionها؛ همه زمان‌ها شمسی هستند.</p></div><button className="btn-secondary mr-auto" onClick={()=>load().catch(e=>setError(e.message))}><RefreshCw size={16}/>بروزرسانی</button></div>
  {users.length>0&&<section className="card mt-6 p-4"><label className="label">کاربر</label><select className="input max-w-md" value={selected} onChange={e=>{setSelected(e.target.value);load(e.target.value).catch(x=>setError(x.message))}}><option value="">حساب خودم</option>{users.filter(u=>u.id!==currentUserId).map(u=><option key={u.id} value={u.id}>{u.name} · {u.email}</option>)}</select></section>}
  {!selected&&<section className="card mt-4 p-5"><div className="flex flex-wrap items-start gap-4"><div className="rounded-xl bg-brand-50 p-3 text-brand-700"><KeyRound/></div><div className="flex-1"><div className="flex items-center gap-2"><h2 className="font-bold">ورود دومرحله‌ای</h2><span className={`badge ${twoFactor.enabled?'bg-emerald-50 text-emerald-700':'bg-slate-100 text-slate-600'}`}>{twoFactor.enabled?'فعال':'غیرفعال'}</span></div><p className="mt-1 text-xs text-slate-500">سازگار با Google Authenticator، Microsoft Authenticator و برنامه‌های استاندارد TOTP.</p>{twoFactor.enabled&&<p className="mt-2 text-xs text-slate-500">Recovery Code باقی‌مانده: {twoFactor.recoveryCodesRemaining.toLocaleString('fa-IR')}</p>}</div>{!twoFactor.enabled&&!qr&&<button className="btn-primary" disabled={busy} onClick={begin2fa}>فعال‌سازی 2FA</button>}</div>
  {qr&&<div className="mt-5 grid gap-5 border-t pt-5 md:grid-cols-[220px_1fr]"><img src={qr} alt="QR ورود دومرحله‌ای" className="h-52 w-52 rounded-xl border bg-white p-2"/><div><p className="text-sm leading-7 text-slate-600">QR را با برنامه Authenticator اسکن کن و بعد کد ۶ رقمی تولیدشده را وارد کن.</p><div className="mt-3 rounded-xl bg-slate-50 p-3 text-xs text-slate-500"><span className="block">Secret دستی:</span><code className="break-all select-all">{secret}</code></div><div className="mt-4 flex gap-2"><input className="input max-w-xs" inputMode="numeric" autoComplete="one-time-code" value={code} onChange={e=>setCode(e.target.value)} placeholder="کد ۶ رقمی"/><button className="btn-primary" disabled={busy||!code} onClick={confirm2fa}>تأیید و فعال‌سازی</button></div></div></div>}
  {twoFactor.enabled&&<div className="mt-5 border-t pt-5"><p className="mb-2 text-xs text-slate-500">برای غیرفعال‌کردن 2FA یک کد TOTP یا Recovery Code معتبر وارد کن.</p><div className="flex gap-2"><input className="input max-w-xs" value={code} onChange={e=>setCode(e.target.value)} placeholder="کد امنیتی"/><button className="btn-secondary" disabled={busy||!code} onClick={disable2fa}>غیرفعال‌سازی 2FA</button></div></div>}
  {recoveryCodes.length>0&&<div className="mt-5 rounded-xl border border-amber-200 bg-amber-50 p-4"><b className="text-sm text-amber-800">Recovery Codeها را همین حالا در جای امن ذخیره کن؛ فقط این یک‌بار نمایش داده می‌شوند.</b><div className="mt-3 grid gap-2 sm:grid-cols-2">{recoveryCodes.map(x=><code key={x} className="rounded-lg bg-white p-2 text-center text-sm font-bold">{x}</code>)}</div></div>}
  </section>}
  <section className="card mt-4 p-5"><div className="flex flex-wrap items-center gap-3"><div><h2 className="font-bold">Sessionها</h2><p className="mt-1 text-xs text-slate-500">این عملیات تمام JWTهای قبلی این حساب را بی‌اعتبار می‌کند.</p></div><button className="btn-primary mr-auto" disabled={busy} onClick={revoke}><LogOut size={16}/>{busy?'در حال خروج...':selected?'خروج این کاربر از همه دستگاه‌ها':'خروج من از همه دستگاه‌ها'}</button></div></section>
  {error&&<div className="mt-4 rounded-xl bg-red-50 p-3 text-sm text-red-700">{error}</div>}
  <section className="card mt-4 overflow-hidden"><div className="border-b p-4"><b>تاریخچه ورود</b></div><div className="divide-y">{events.map(ev=><div key={ev.id} className="flex gap-3 p-4"><div className={`grid h-10 w-10 shrink-0 place-items-center rounded-xl ${ev.success?'bg-emerald-50 text-emerald-700':'bg-red-50 text-red-700'}`}>{ev.success?<ShieldCheck size={18}/>:<ShieldX size={18}/>}</div><div className="min-w-0 flex-1"><div className="flex flex-wrap items-center gap-2"><b className="text-sm">{reasonLabels[ev.reason||'']||ev.reason||'رویداد امنیتی'}</b><span className={`badge ${ev.success?'bg-emerald-50 text-emerald-700':'bg-red-50 text-red-700'}`}>{ev.success?'موفق':'ناموفق'}</span></div><p className="mt-1 text-xs text-slate-500">{formatPersianDateTime(ev.createdAt)} · IP: {ev.ip||'—'}</p><p className="mt-1 truncate text-[11px] text-slate-400" title={ev.userAgent||''}>{ev.userAgent||'User-Agent ثبت نشده'}</p></div></div>)}{!events.length&&<div className="p-10 text-center text-sm text-slate-500">هنوز رویداد امنیتی ثبت نشده است.</div>}</div></section></div>}
