'use client';
import {FormEvent,useEffect,useState} from 'react';
import {ShieldCheck,Users} from 'lucide-react';

type UserItem={id:string;name:string;email:string;role:'SYSTEM_ADMIN'|'AGENCY_MANAGER'|'AGENT'};
type SettingsData={mode:'demo'|'database';agency:{id:string;name:string}|null;users:UserItem[]};
const roleLabels={SYSTEM_ADMIN:'مدیر سیستم',AGENCY_MANAGER:'مدیر آژانس',AGENT:'مشاور املاک'};

export function SettingsView(){
  const[data,setData]=useState<SettingsData|null>(null);const[error,setError]=useState('');const[saving,setSaving]=useState('');const[agencyName,setAgencyName]=useState('');
  async function load(){try{setError('');const r=await fetch('/api/settings',{cache:'no-store'});const j=await r.json();if(!r.ok)throw new Error(j.error);setData(j.data);setAgencyName(j.data.agency?.name??'');}catch(e){setError(e instanceof Error?e.message:'خطا در دریافت تنظیمات')}}
  useEffect(()=>{load()},[]);
  async function saveAgency(e:FormEvent){e.preventDefault();setSaving('agency');setError('');try{const r=await fetch('/api/settings',{method:'PATCH',headers:{'Content-Type':'application/json'},body:JSON.stringify({type:'agency',name:agencyName})});const j=await r.json();if(!r.ok)throw new Error(j.error);setData(d=>d?{...d,agency:j.data}:d);}catch(e){setError(e instanceof Error?e.message:'خطا در ذخیره تنظیمات')}finally{setSaving('')}}
  async function changeRole(id:string,role:UserItem['role']){setSaving(id);setError('');try{const r=await fetch('/api/settings',{method:'PATCH',headers:{'Content-Type':'application/json'},body:JSON.stringify({type:'user-role',id,role})});const j=await r.json();if(!r.ok)throw new Error(j.error);setData(d=>d?{...d,users:d.users.map(u=>u.id===id?{...u,role:j.data.role}:u)}:d);}catch(e){setError(e instanceof Error?e.message:'خطا در تغییر سطح دسترسی')}finally{setSaving('')}}
  return <><h1 className="text-2xl font-bold">تنظیمات</h1><p className="mt-1 text-sm text-slate-500">مدیریت آژانس، کاربران و سطح دسترسی</p>{error&&<div className="card mt-5 p-4 text-red-600">{error}</div>}{!data&&!error&&<div className="card mt-6 p-8 text-center text-slate-500">در حال دریافت تنظیمات...</div>}{data&&<div className="mt-6 grid gap-5 xl:grid-cols-3"><form onSubmit={saveAgency} className="card p-6 xl:col-span-1"><div className="mb-5 flex items-center gap-2"><ShieldCheck className="text-brand-600"/><h2 className="font-bold">اطلاعات آژانس</h2></div><label className="label">نام آژانس</label><input className="input" value={agencyName} onChange={e=>setAgencyName(e.target.value)} required/><label className="label mt-4">حالت برنامه</label><input className="input" disabled value={data.mode==='demo'?'نمایشی (Demo Mode)':'دیتابیس واقعی'}/><button className="btn-primary mt-5 w-full" disabled={saving==='agency'}>{saving==='agency'?'در حال ذخیره...':'ذخیره نام آژانس'}</button></form><div className="card p-6 xl:col-span-2"><div className="mb-5 flex items-center gap-2"><Users className="text-brand-600"/><h2 className="font-bold">کاربران و سطح دسترسی</h2></div>{data.users.length===0?<p className="text-sm text-slate-500">هنوز کاربری ثبت نشده است.</p>:<div className="space-y-3">{data.users.map(u=><div key={u.id} className="flex flex-col gap-3 rounded-xl border p-4 md:flex-row md:items-center"><div><b>{u.name}</b><p className="text-xs text-slate-500">{u.email}</p></div><div className="md:mr-auto md:w-48"><select className="input" value={u.role} disabled={saving===u.id} onChange={e=>changeRole(u.id,e.target.value as UserItem['role'])}><option value="AGENT">{roleLabels.AGENT}</option><option value="AGENCY_MANAGER">{roleLabels.AGENCY_MANAGER}</option><option value="SYSTEM_ADMIN">{roleLabels.SYSTEM_ADMIN}</option></select></div></div>)}</div>}</div></div>}</>;
}
