import { prisma, isDemoMode } from '@/lib/prisma';
import type { DataActor } from '@/lib/data-scope';
import { enqueueAutomationJob } from '@/lib/automation/job-queue';

type EventName = 'VISIT_COMPLETED' | 'APPLICANT_CREATED' | 'STAGE_CHANGED' | 'FOLLOWUP_COMPLETED';
type CRMEvent = { name: EventName; actor: DataActor; entityType: 'APPLICANT' | 'FOLLOWUP'; entityId: string; assigneeId: string; href?: string; data: Record<string,string|number|boolean|null|undefined>; occurredAt?: Date };
type Condition = { field:string; operator:string; value:string|number|boolean };
function matchesCondition(c:Condition,data:CRMEvent['data']){const current=data[c.field],expected=c.value;switch(c.operator){case'EQ':return String(current??'')===String(expected);case'NEQ':return String(current??'')!==String(expected);case'GTE':return Number(current)>=Number(expected);case'LTE':return Number(current)<=Number(expected);default:return false}}
export async function dispatchCRMEvent(event:CRMEvent){if(isDemoMode||!event.actor.agencyId)return[];const rules=await prisma.automationRule.findMany({where:{agencyId:event.actor.agencyId,enabled:true,custom:true}});const matched=rules.filter(rule=>{const trigger=(rule.trigger??{})as{event?:string;delayHours?:number};if(trigger.event!==event.name)return false;const conditions=Array.isArray(rule.conditions)?rule.conditions as unknown as Condition[]:[];return conditions.every(c=>matchesCondition(c,event.data))});const occurredAt=event.occurredAt??new Date();const results=[];for(const rule of matched){const trigger=(rule.trigger??{})as{delayHours?:number};const delayHours=Math.max(0,Number(trigger.delayHours??0));const runAt=new Date(occurredAt.getTime()+delayHours*3600000);const eventFingerprint=`${event.name}:${event.entityType}:${event.entityId}:${occurredAt.toISOString().slice(0,16)}`;const message=rule.description||`Rule «${rule.name}» برای این رویداد اجرا شد.`;const job=await enqueueAutomationJob({key:`automation-job:${rule.id}:${eventFingerprint}`,agencyId:event.actor.agencyId,runAt,payload:{ruleId:rule.id,ruleName:rule.name,action:rule.action,priority:rule.priority,message,assigneeId:event.assigneeId,entityType:event.entityType,entityId:event.entityId,href:event.href,actorId:event.actor.id,eventName:event.name,eventFingerprint}});await prisma.activityLog.create({data:{actorId:event.actor.id,action:'AUTOMATION_QUEUED',entityType:event.entityType,entityId:event.entityId,summary:`اتوماسیون ${rule.name} برای اجرا صف‌بندی شد`,metadata:{ruleId:rule.id,event:event.name,runAt:runAt.toISOString(),delayHours}}});results.push(job)}return results}
