import type { Prisma } from '@prisma/client';
import { prisma } from '@/lib/prisma';
import type { DataActor } from '@/lib/data-scope';

export type MatchingConfig={weights:{deal:number;budget:number;city:number;district:number;propertyType:number;rooms:number;features:number;active:number};hard:{deal:boolean;maxBudget:boolean;city:boolean;propertyType:boolean;minRooms:boolean};feedback:{positiveBoost:number;negativePenalty:number}};
export const defaultMatchingConfig:MatchingConfig={weights:{deal:20,budget:30,city:10,district:20,propertyType:10,rooms:5,features:5,active:5},hard:{deal:true,maxBudget:false,city:false,propertyType:false,minRooms:false},feedback:{positiveBoost:8,negativePenalty:12}};
function mergeConfig(value:Prisma.JsonValue|null|undefined):MatchingConfig{const raw=(value&&typeof value==='object'&&!Array.isArray(value)?value:{}) as any;return{weights:{...defaultMatchingConfig.weights,...(raw.weights||{})},hard:{...defaultMatchingConfig.hard,...(raw.hard||{})},feedback:{...defaultMatchingConfig.feedback,...(raw.feedback||{})}}}
export async function getMatchingConfig(actor:DataActor){if(!actor.agencyId)return defaultMatchingConfig;const agency=await prisma.agency.findUnique({where:{id:actor.agencyId},select:{matchingConfig:true}});return mergeConfig(agency?.matchingConfig)}
export async function saveMatchingConfig(actor:DataActor,input:MatchingConfig){if(actor.role==='AGENT'||!actor.agencyId)throw new Error('FORBIDDEN');const clamp=(n:number,min=0,max=100)=>Math.max(min,Math.min(max,Math.round(Number(n)||0)));const config:MatchingConfig={weights:{deal:clamp(input.weights.deal),budget:clamp(input.weights.budget),city:clamp(input.weights.city),district:clamp(input.weights.district),propertyType:clamp(input.weights.propertyType),rooms:clamp(input.weights.rooms),features:clamp(input.weights.features),active:clamp(input.weights.active)},hard:{deal:Boolean(input.hard.deal),maxBudget:Boolean(input.hard.maxBudget),city:Boolean(input.hard.city),propertyType:Boolean(input.hard.propertyType),minRooms:Boolean(input.hard.minRooms)},feedback:{positiveBoost:clamp(input.feedback.positiveBoost,0,30),negativePenalty:clamp(input.feedback.negativePenalty,0,30)}};await prisma.agency.update({where:{id:actor.agencyId},data:{matchingConfig:config as Prisma.InputJsonValue}});return config}
